//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuntiLeimausMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Luokkahuone
    {
        public int LuokkahuoneID { get; set; }
        public string Luokkahuone1 { get; set; }
    }
}
