//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuntiLeimaus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuntiraportti
    {
        public int OpiskelijaID { get; set; }
        public string Etunimi { get; set; }
        public string Sukunimi { get; set; }
        public Nullable<int> LuokkahuoneID { get; set; }
        public Nullable<System.DateTime> Sisään { get; set; }
        public Nullable<System.DateTime> Ulos { get; set; }
    }
}
